#!/bin/sh

if ! git diff --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
  echo "Commit rejected: there are unstaged or untracked changes."
  echo "Stage everything or stash before committing."
  echo ""
  echo "For stashing:"
  echo ""
  echo "  git stash --keep-index --include-untracked"
  echo "  git commit"
  echo "  git stash pop"
  exit 1
fi

make autofix
git add .
make check
